name: format

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

permissions:
  contents: read
  security-events: write

jobs:
  analyze:
    name: Check code formatting
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci-skip-format') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Run linters
        run: |
          buildscripts/clang_format.py format
          buildscripts/pylinters.py fix
          buildscripts/pylinters.py fix-scons
          buildscripts/eslint.py fix

      - name: Verify formatting
        run: |
          if ! git diff --quiet; then
            echo "::error::Formatting issues detected."
            echo ""
            echo "Your PR is not properly formatted."
            echo ""
            echo "To fix the problem locally, run:"
            echo ""
            echo "    bazel run format"
            echo ""
            echo "and commit the resulting changes."
            echo ""
            echo "Affected files:"
            git diff --stat
            echo "Diff:"
            git diff | head -n 1000
            exit 1
          fi
